---
title: "Exploratory Data Analysis: Numeric summaries"
author: "Sarah Haberlack"
date: "2023-10-06"
output: github_document
---

```{r setup and load libraries, include=FALSE}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = .6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month" )) |>
  select(name, id, everything())

weather_df
```

## Initial numeric work

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

here are the big outliers:
```{r}
weather_df |> 
  filter(prcp > 1000)
```

